In [2]:
import numpy as np
import pandas as pd
import openpyxl as op

In [3]:
new = pd.read_excel(r'D:\ITI\FinalProject\data\البيانات النهائية النسخه معدله.xlsx')
old = pd.read_excel(r'D:\ITI\FinalProject\data\final_cleaned_data.xlsx')

In [4]:
new.head()

,INDIVIDUAL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,EDUCATION,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,SURVEY_INFO,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,RESPONSEID,PARENTRESPONSEID,GOV,GENDER,AGE,MARITAL,UR,RELATION,EDU,EDUCATION_JOIN,...,CONTRACT_PERIOD,WORK_PLACE,EST_INDS_REG_COMM,EST_INSURANCE,QUARTER,AGE_CODE,AGE_GROUP,TRAINING_COURSE,occupation_group,JOB_NORM
1,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,السويس,ذكر,38,متزوج/ة,حضر,رئيس الأسرة,ثانوي فني,خريج أنهى الدراسة,...,من 3 شهور إلى 12 شهراً,داخل المنشأة,لا - غير مسجل,لا - غير مؤمن,1,NaN,30-34 سنة,لا - لم يلتحق,نقل ومواصلات,سائق اتوبيس
2,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,البحيرة,أنثى,37,متزوج/ة,ريف,زوج/زوجة,يقرأ ويكتب,التحق ولم يكمل,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),30-34 سنة,لا - لم يلتحق,لايوجد,NaN
3,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,الجيزة,ذكر,28,أعزب/عزباء,حضر,ابن/ابنة,ثانوي فني,خريج أنهى الدراسة,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),25-29 سنة,لا - لم يلتحق,لايوجد,NaN
4,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,كفر الشيخ,ذكر,9,NaN,حضر,ابن/ابنة,أقل من السن,ملتحق حالياً,...,NaN,NaN,NaN,NaN,1,25-49 سنة (منتصف العمر),15-19 سنة,لا - لم يلتحق,لايوجد,NaN

In [5]:
new.columns = new.iloc[0]
new = new[1:].reset_index(drop=True)

In [6]:
new.head()

,RESPONSEID,PARENTRESPONSEID,GOV,GENDER,AGE,MARITAL,UR,RELATION,EDU,EDUCATION_JOIN,...,CONTRACT_PERIOD,WORK_PLACE,EST_INDS_REG_COMM,EST_INSURANCE,QUARTER,AGE_CODE,AGE_GROUP,TRAINING_COURSE,occupation_group,JOB_NORM
0,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,السويس,ذكر,38,متزوج/ة,حضر,رئيس الأسرة,ثانوي فني,خريج أنهى الدراسة,...,من 3 شهور إلى 12 شهراً,داخل المنشأة,لا - غير مسجل,لا - غير مؤمن,1,NaN,30-34 سنة,لا - لم يلتحق,نقل ومواصلات,سائق اتوبيس
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,البحيرة,أنثى,37,متزوج/ة,ريف,زوج/زوجة,يقرأ ويكتب,التحق ولم يكمل,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),30-34 سنة,لا - لم يلتحق,لايوجد,NaN
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,الجيزة,ذكر,28,أعزب/عزباء,حضر,ابن/ابنة,ثانوي فني,خريج أنهى الدراسة,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),25-29 سنة,لا - لم يلتحق,لايوجد,NaN
3,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,كفر الشيخ,ذكر,9,NaN,حضر,ابن/ابنة,أقل من السن,ملتحق حالياً,...,NaN,NaN,NaN,NaN,1,25-49 سنة (منتصف العمر),15-19 سنة,لا - لم يلتحق,لايوجد,NaN
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,52CDDE65-7225-4717-BB8A-D1F713ADD602,المنوفية,أنثى,80,أرمل/ة,ريف,أب/أم,أمي,لم يلتحق مطلقاً,...,NaN,NaN,NaN,NaN,1,25-49 سنة (منتصف العمر),45-49 سنة,لا - لم يلتحق,لايوجد,NaN

In [7]:
old.head()

,response_id,GOV_CODE,governorate_code,survey_station_code,section_code,urban_rural_code,member_id,relationship_to_head_code,gender_code,birth_month,...,main_reason_not_searching_work_code,ever_worked_code,last_job,last_activity,sector_code,reason_stopped_working_code,stop_work_month,survey_quarter,occupation_group,JOB_NORM
0,31AE82A8-95D7-4E66-876D-8031121996A2,4,السويس,404,40401,حضر,1,رئيس الأسرة,ذكر,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,نقل ومواصلات,سائق اتوبيس
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,18,البحيرة,1809,180918,ريف,2,زوج / زوجة,أنثى,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,لايوجد,NaN
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,21,الجيزة,2105,210503,حضر,5,ابن / ابنة,ذكر,7.0,...,NaN,سبق له العمل,سمكري سيارات,تصليح وصيانة السيارات,خاص,إغالق العمل أو المنشأة,3.0,1,لايوجد,NaN
3,1512A995-F9F6-4369-A967-6806B446B1F2,15,كفر الشيخ,1502,150201,حضر,4,ابن / ابنة,ذكر,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,لايوجد,NaN
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,17,المنوفية,1705,170522,ريف,3,أب / أم,أنثى,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,لايوجد,NaN

In [8]:
new['SALARY'] = old['calculated_salary']

In [9]:
new['SALARY'].head(10)

0    3500
1       0
2       0
3       0
4       0
5    3000
6       0
7       0
8       0
9       0
Name: SALARY, dtype: int64

In [10]:
new.shape

(296724, 70)

In [11]:
old.shape

(296724, 68)

In [12]:
new

,RESPONSEID,PARENTRESPONSEID,GOV,GENDER,AGE,MARITAL,UR,RELATION,EDU,EDUCATION_JOIN,...,CONTRACT_PERIOD,WORK_PLACE,EST_INDS_REG_COMM,EST_INSURANCE,QUARTER,AGE_CODE,AGE_GROUP,TRAINING_COURSE,occupation_group,JOB_NORM
0,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,السويس,ذكر,38,متزوج/ة,حضر,رئيس الأسرة,ثانوي فني,خريج أنهى الدراسة,...,من 3 شهور إلى 12 شهراً,داخل المنشأة,لا - غير مسجل,لا - غير مؤمن,1,NaN,30-34 سنة,لا - لم يلتحق,نقل ومواصلات,سائق اتوبيس
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,البحيرة,أنثى,37,متزوج/ة,ريف,زوج/زوجة,يقرأ ويكتب,التحق ولم يكمل,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),30-34 سنة,لا - لم يلتحق,لايوجد,NaN
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,الجيزة,ذكر,28,أعزب/عزباء,حضر,ابن/ابنة,ثانوي فني,خريج أنهى الدراسة,...,NaN,NaN,NaN,NaN,1,15-24 سنة (الشباب),25-29 سنة,لا - لم يلتحق,لايوجد,NaN
3,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,كفر الشيخ,ذكر,9,NaN,حضر,ابن/ابنة,أقل من السن,ملتحق حالياً,...,NaN,NaN,NaN,NaN,1,25-49 سنة (منتصف العمر),15-19 سنة,لا - لم يلتحق,لايوجد,NaN
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,52CDDE65-7225-4717-BB8A-D1F713ADD602,المنوفية,أنثى,80,أرمل/ة,ريف,أب/أم,أمي,لم يلتحق مطلقاً,...,NaN,NaN,NaN,NaN,1,25-49 سنة (منتصف العمر),45-49 سنة,لا - لم يلتحق,لايوجد,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296719,EC9B3617-2A83-4BF5-AC76-12BA0C8F488D,8DB7A2D8-5474-4936-8931-F2D106D4D970,القليوبية,أنثى,19,أعزب/عزباء,حضر,ابن/ابنة,ثانوية عامة,ملتحق حالياً,...,NaN,NaN,NaN,NaN,4,15-24 سنة (الشباب),20-24 سنة,لا - لم يلتحق,لايوجد,NaN
296720,05AE321C-908A-48B9-B785-4ED4C0A6DE8F,76B18629-8A0A-4135-92EA-29DE75088EF5,الجيزة,أنثى,42,متزوج/ة,ريف,زوج/زوجة,يقرأ ويكتب,التحق ولم يكمل,...,NaN,NaN,NaN,NaN,4,15-24 سنة (الشباب),30-34 سنة,لا - لم يلتحق,لايوجد,NaN
296721,411B88A4-C384-4B03-BCCF-4EEC8AB08495,9408D533-A347-4CBC-ADD7-4C15906A1720,أسيوط,أنثى,25,متزوج/ة,حضر,زوج/زوجة,مؤهل جامعي,خريج أنهى الدراسة,...,NaN,NaN,NaN,NaN,4,15-24 سنة (الشباب),25-29 سنة,لا - لم يلتحق,لايوجد,NaN
296722,665DAA91-B90A-4A81-A612-4F4FC284BA34,0E79D069-08A2-46C5-B062-50DB7522E7E3,المنوفية,ذكر,39,أعزب/عزباء,حضر,رئيس الأسرة,ثانوي فني,خريج أنهى الدراسة,...,أقل من 3 شهور,خارج المنشأة,نعم - مسجل رسمياً,نعم - مؤمن عليه,4,NaN,30-34 سنة,لا - لم يلتحق,نقل ومواصلات,سائق سائق توك توك
296723,FC5696A6-6A8E-4AB2-A49B-02FFC449ABBD,9AA32D23-A6D4-476E-99F1-DD7866C6A416,الشرقية,ذكر,31,متزوج/ة,ريف,رئيس الأسرة,ثانوي فني,خريج أنهى الدراسة,...,أكثر من 36 شهراً,خارج المنشأة,نعم - مسجل رسمياً,نعم - مؤمن عليه,4,NaN,25-29 سنة,لا - لم يلتحق,بناء وتشييد,سباك

In [13]:
new['AGE'].value_counts()

AGE
5      8014
10     7515
9      7380
11     7217
12     7107
       ...
101       4
96        3
98        3
99        3
97        1
Name: count, Length: 102, dtype: int64

In [14]:
new[new['AGE'] < 5]

,RESPONSEID,PARENTRESPONSEID,GOV,GENDER,AGE,MARITAL,UR,RELATION,EDU,EDUCATION_JOIN,...,CONTRACT_PERIOD,WORK_PLACE,EST_INDS_REG_COMM,EST_INSURANCE,QUARTER,AGE_CODE,AGE_GROUP,TRAINING_COURSE,occupation_group,JOB_NORM
23,0302C167-FA0C-45C8-AA96-0FA968FB9B0E,DD5B37B9-85B6-45C9-BBD8-E006BB1A1D1A,أسيوط,أنثى,1,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,15-19 سنة,نعم - التحق بدورة تدريبية,لايوجد,NaN
36,1F8D4DD1-11FA-4706-B29A-6D13033FD760,A9CD06A7-2D4A-4FB1-9E2F-79393FCE2285,بني سويف,ذكر,0,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,لا - لم يلتحق,لايوجد,NaN
39,663DB94F-5551-4AAB-819A-F4A48BE6DF7A,22B0EF33-63DF-4973-B8F2-2D07F0C20938,الدقهلية,ذكر,2,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,15-19 سنة,نعم - التحق بدورة تدريبية,لايوجد,NaN
43,62B790B3-421E-4DBA-9D73-9376429797CF,E8843C25-3812-4DFF-9542-DC77916B187C,جنوب سيناء,ذكر,3,NaN,حضر,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,15-19 سنة,لا - لم يلتحق,لايوجد,NaN
45,87372FEC-82D2-4B1C-AF76-E54E15C6BC96,313F6A5A-0E5F-4E95-9F41-720AE792809F,الفيوم,أنثى,3,NaN,حضر,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,15-19 سنة,لا - لم يلتحق,لايوجد,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296649,FEF901BB-B564-4658-9D86-FA9BDEDDABB5,5B24CB2D-9B47-45B8-A7D2-BA5D1DDEDB85,البحيرة,أنثى,3,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,15-19 سنة,لا - لم يلتحق,لايوجد,NaN
296661,E0BE18E2-10EF-4929-A9FE-078E7B6EDFE1,9214575B-DFF0-495B-AEAD-15A4C65A2ACD,الإسكندرية,أنثى,1,NaN,حضر,حفيد/حفيدة,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,15-19 سنة,نعم - التحق بدورة تدريبية,لايوجد,NaN
296687,13A242BA-0F8A-41B0-A203-9D3B52C105E9,25F8CFA6-CBA5-4564-9859-C92DD11B9252,سوهاج,ذكر,1,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,15-19 سنة,لا - لم يلتحق,لايوجد,NaN
296710,C671365C-C425-4CFE-BECE-1CE28423C012,482A06B1-CBEE-4B6F-AA64-50E44DF16E68,الفيوم,ذكر,0,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,NaN,لا - لم يلتحق,لايوجد,NaN
296713,2E97FD43-EB32-4BDB-8933-1273326C12EE,0E2D6C3B-57AC-4355-BBD1-AB22D258AC87,سوهاج,ذكر,3,NaN,ريف,ابن/ابنة,NaN,NaN,...,NaN,NaN,NaN,NaN,4,NaN,15-19 سنة,لا - لم يلتحق,لايوجد,NaN