In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\ITI\FinalProject\data\member_info_2024_last.csv")
df.head()

C:\Users\abdel\AppData\Local\Temp\ipykernel_16108\720595194.py:1: DtypeWarning: Columns (0: MEMBER_CODE, 1: EDU_LEAVE_REASON_OTHER, 2: PLACE_COURSE_OTHER, 3: COURSE_SUBJECT_OTHER, 4: REASON_TRAINING_OTHER, 5: PREV_CHANGE_REASON_OTHER, 6: WORK_PREVENT_REASON_OTHER, 7: SECTOR_OTHER_1, 8: TEXT_229_I_H, 9: WORK_SECOND_TARMEZ, 10: PLACE_OTHER, 11: SEARCH_WORK_FIRST_OTHER, 12: SEARCH_WORK_SECOND_OTHER, 13: MAIN_REASON_NO_SEARCH_OTHER, 14: SECTOR_OTHER, 15: REASON_STOP_WORK_OTHER, 16: UNPAID_WORK_TYPE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\ITI\FinalProject\data\member_info_2024_last.csv")

,RESPONSEID,PARENTRESPONSEID,DOMAINID,PHASEID,CREATIONPHASEID,GOV_CODE,STATION_CODE,SECTION_CODE,UR_CODE,MEMBER_CODE,...,ACT_SECOND_TARMEZ,EMP_CODE,EMP_CODE_1,EMP_CODE_2,EMP_CODE_3,EMP_CODE_4,ORIGINAL,NORMAL,QUARTER,ORIGINAL_QUARTER
0,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,F5F1BE0A-C2D1-4DFE-9ACC-3DA0C151F80E,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,4,404,40401,1.0,1,...,NaN,1.0,1.0,NaN,NaN,NaN,224.842430,0.158556,1.0,899.369721
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,E3DD23B1-0560-4AAB-997A-1350432F71DE,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,18,1809,180918,2.0,2,...,NaN,3.0,NaN,NaN,1.0,NaN,383.212208,0.270237,1.0,1532.848834
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,0FD12B99-88F0-4A60-9FBC-83E71FEFD750,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,21,2105,210503,1.0,5,...,NaN,2.0,NaN,1.0,NaN,NaN,431.231027,0.304099,1.0,1724.924109
3,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,3DFDF17A-5F59-40E7-97D6-17C0FBB71126,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,15,1502,150201,1.0,4,...,NaN,3.0,NaN,NaN,1.0,NaN,336.670043,0.237416,1.0,1346.680171
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,52CDDE65-7225-4717-BB8A-D1F713ADD602,7C5ADABA-56A3-41A2-A1F3-10B442F9C8DB,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,17,1705,170522,2.0,3,...,NaN,4.0,NaN,NaN,NaN,1.0,200.729200,0.141552,1.0,802.916802

In [3]:
df.isna().sum() / len(df) * 100 > 75

RESPONSEID          False
PARENTRESPONSEID    False
DOMAINID            False
PHASEID             False
CREATIONPHASEID     False
                    ...
EMP_CODE_4           True
ORIGINAL            False
NORMAL              False
QUARTER             False
ORIGINAL_QUARTER    False
Length: 235, dtype: bool

In [4]:
columns_to_drop = [
    'NAME_PERSON_FAMILY',
    'NOTCHIL_REGISTERED_CD',
    'NOT_PERSON_FAMILY_CODE',
    'EDU_LEAVE_REASON_OTHER',
    'GRADE1',
    'MARITAL_CONFIRM_FEMALE',
    'PLACE_COURSE_OTHER',
    'COURSE_SUBJECT_OTHER',
    'TRAINING_PERIOD_LESSMONTH',
    'TIME_RECYCLE',
    'REASON_TRAINING_OTHER',
    'UNDERSTANDING_CODE',
    'CHANGE_STAY_CODE',
    'OUT_IN_CODE',
    'PREV_PLACE_CODE',
    'PREV_PLACE_OUT',
    'PREV_CHANGE_YEAR',
    'PREV_CHANGE_REASON_CODE',
    'PREV_CHANGE_REASON_OTHER',
    'LAST_SMOKING_CODE',
    'LAST_DAY_SMOKING_CODE',
    'EDU_TRMEZ_REVIEW_CODE',
    'NOTICE',
    'NOT_ANSWER_HIMSELF',
    'PAID_WORK_TYPE_CODE',
    'WORK_PREVENT_REASON',
    'WORK_PREVENT_REASON_OTHER',
    'ABSENT_DURATION',
    'Q_204_A',
    'DECISIOMAKER',
    'HIRE_AWORKER_3MONTH',
    'ENTITYPROVIDE',
    'REGISTEREDOFFICIALRECORDS',
    'MANAGEPROJECT',
    'EST_NAME',
    'WORK_TYPE_CODE',
    'URCODE',
    'SECTOR_OTHER_1',
    'YEAR_NO',
    'VACATIONS_ILLNESS_CODE',
    'INDEMNITY_CODE',
    'CONTRACT_PERIOD_CODE',
    'FIXEDWAGE',
    'PAYWORKCOMPLETED',
    'COMMISSIONS',
    'TIPPING_GRATUITY',
    'FEES_EACHSERVICE',
    'NON_FINANCIALCONSIDERATION',
    'OTHER_229_H',
    'TEXT_229_I_H',
    'DONTGETPAID',
    'EST_ACCOUNTING_CODE',
    'EST_INDS_REG_COMM_CODE',
    'EST_INSURANCE_CODE',
    'WORK_ORG_FAM_CODE',
    'WORK_SECOND_TARMEZ',
    'TOT_EMP_CODE',
    'EST_ACCOUN_SECOND_CODE',
    'EST_INDS_REG_COM_SCND_CD',
    'EST_INSURANCE_SCND_CODE',
    'WRK_ORG_FAM_SCND_CODE',
    'PLACE_OTHER',
    'EXCH_PERIOD_SCND_CD',
    'ADD_HOUR_NO',
    'HOUR_SECOND_NO',
    'ADD_HOUR_CODE',
    'SRCH_PS_WK4_WRK_ADD_CD',
    'SEARCH_WEEK4_WORK_CODE',
    'COMMENT1',
    'START_WORK_CODE',
    'NO_DESIRE_OTHER',
    'SEARCH_WORK_WITHOUT_LIMT',
    'SEARCH_WORK_CODE',
    'SEARCH_WORK_FIRST_CODE',
    'SEARCH_WORK_FIRST',
    'SEARCH_WORK_FIRST_OTHER',
    'SEARCH_WORK_SECOND_CODE',
    'SEARCH_WORK_SECOND',
    'SEARCH_WORK_SECOND_OTHER',
    'SEARCH_WORK_THIRD_CODE',
    'SEARCH_WORK_THIRD',
    'SEARCH_WORK_THIRD_OTHER',
    'WORK_CODE',
    'MAIN_REASON_NO_SEARCH_OTHER',
    'GIVER_CODE_C',
    'EVER_WORK_CODE_1',
    'COMMENT_WRITE',
    'LAST_WORK',
    'LAST_ACT',
    'SECTOR_OTHER',
    'WORK_PLACE_CODE_CORONA',
    'REASON_STOP_WORK_CODE',
    'REASON_STOP_WORK_OTHER',
    'STOP_WORK_COUSECORONA',
    'STOP_WORK_MONTH',
    'REFUSED_JOP',
    'REFUSED_JOP_REASON_CODE',
    'REFUSED_JOP_REASON_OTHER',
    'PROBLEM_WORK_CODE',
    'PROBLEM_WORK_OTHER',
    'JOBTRZ_REV_CD_LST_WRK',
    'JOB_TRMEZ_CODE_LAST_WORK',
    'LST_ACT_TRZ_REV_CD',
    'LAST_ACT_TRMEZ_CODE',
    'GIVER_DESCRIPTION_CODE',
    'PRACTICE_UNPAID_ACT_CODE',
    'UNPAID_ACT_CODE',
    'WORK_ENTITY_CODE',
    'UNPAID_WORK_TYPE',
    'MJORUNPAIDOCCUPATIONREV',
    'MAINOCCUPUNPAIDINDVUA',
    'UNPAID_HOUR_NO',
    'ACT_SECOND_TARMEZ',
    'ORIGINAL',
    'NORMAL',
    'QUARTER',
    'ORIGINAL_QUARTER',
]

In [5]:
df.drop(columns=columns_to_drop, inplace=True)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Columns: 118 entries, RESPONSEID to EMP_CODE_4
dtypes: float64(97), int64(9), object(1), str(11)
memory usage: 267.1+ MB

In [7]:
df.drop(columns = [col for col in df.columns if 'HOUSE_CONSUME_' in col], inplace=True)

In [8]:
df.drop(columns = [col for col in df.columns if 'EMP_CODE' in col], inplace=True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Columns: 104 entries, RESPONSEID to HOUR_CONSUME_9_NO
dtypes: float64(83), int64(9), object(1), str(11)
memory usage: 235.4+ MB

In [10]:
df.isna().sum() / len(df) * 100

RESPONSEID            0.000000
PARENTRESPONSEID      0.000000
DOMAINID              0.000000
PHASEID               0.000000
CREATIONPHASEID       0.000000
                       ...
HOUR_CONSUME_5_NO    92.669956
HOUR_CONSUME_6_NO    99.540988
HOUR_CONSUME_7_NO    99.972702
HOUR_CONSUME_8_NO    99.845985
HOUR_CONSUME_9_NO    99.985508
Length: 104, dtype: float64

In [11]:
df.drop(
    columns = [col for col in df.columns if 'MARKET_CONSUM' in col],
    inplace = True
)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 93 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RESPONSEID                  296724 non-null  str
 1   PARENTRESPONSEID            296724 non-null  str
 2   DOMAINID                    296724 non-null  str
 3   PHASEID                     296724 non-null  str
 4   CREATIONPHASEID             296724 non-null  str
 5   GOV_CODE                    296724 non-null  int64
 6   STATION_CODE                296724 non-null  int64
 7   SECTION_CODE                296724 non-null  int64
 8   UR_CODE                     296724 non-null  float64
 9   MEMBER_CODE                 296724 non-null  object
 10  GIVER_NAME                  296724 non-null  int64
 11  RELATION_CODE               296724 non-null  int64
 12  GENDER_CODE                 296724 non-null  int64
 13  CURRENT_YEAR                296724 non-null  int64
 14  BIRTH_MONTH                 296723 non-null  float64
 15  BIRTH_YEAR                  296722 non-null  float64
 16  REAL_AGE                    296724 non-null  int64
 17  AGE                         296724 non-null  int64
 18  EDUCATION_JOIN_CODE         261200 non-null  float64
 19  EDU_LEAVE_REASON_CODE       78477 non-null   float64
 20  STAGE_CODE                  129797 non-null  float64
 21  GRADE                       129593 non-null  float64
 22  STAGE_CODE1                 0 non-null       float64
 23  EDU_CODE                    261200 non-null  float64
 24  EDUCATION_CODE              90468 non-null   str
 25  QUALIFICATION_CODE          90468 non-null   str
 26  QUALIFICATION_YEAR          90468 non-null   float64
 27  STUDY_YEAR_NO               0 non-null       float64
 28  MARITAL_CODE                235485 non-null  float64
 29  UNEDUCATED_CODE             0 non-null       float64
 30  TRAINING_COURSE_CODE        58358 non-null   float64
 31  PLACE_COURSE_CODE           509 non-null     float64
 32  COURSE_SUBJECT_CODE         509 non-null     float64
 33  COURSE_PERIOD               509 non-null     float64
 34  REASON_TRAINING_CODE        509 non-null     float64
 35  DIFFICULTIES                67013 non-null   float64
 36  SIGHT_CODE                  5258 non-null    float64
 37  HEARING_CODE                5258 non-null    float64
 38  MEMORY_CODE                 5258 non-null    float64
 39  WALKING_CODE                5258 non-null    float64
 40  SELFCARE_CODE               5258 non-null    float64
 41  CURRENTLY_SMOKING_CODE      49492 non-null   float64
 42  EDU_TRMEZ_CODE              90462 non-null   float64
 43  GIVER_NAME_E                261200 non-null  float64
 44  WORK_LAST_WEEK_CODE         261200 non-null  float64
 45  PAID_WORK_CODE              182898 non-null  float64
 46  EVER_WORK_CODE              79218 non-null   float64
 47  DESCRIPWORKCONDITION        79218 non-null   float64
 48  LABOR_FORCE_CODE            79218 non-null   float64
 49  GETYOURCLIENTS              76421 non-null   float64
 50  WORK_PLACE_CODE             79218 non-null   float64
 51  SECTOR_CODE_1               79218 non-null   float64
 52  ACT_OUT_EST                 79218 non-null   str
 53  CURRENT_WORK                79217 non-null   str
 54  START_WORKING               79218 non-null   float64
 55  REDUCE_DAYWORK_CORONA       0 non-null       float64
 56  HOUR_NO                     79218 non-null   float64
 57  INSURANCE_CODE              79218 non-null   float64
 58  INSURANCE_HEALTH_CODE       79218 non-null   float64
 59  VACATIONS_CODE              57021 non-null   float64
 60  WORK_NATURE_CODE            79218 non-null   float64
 61  CONTRACT_CODE               44156 non-null   float64
 62  BACK_208                    79218 non-null   float64
 63  EXCHANGE_PERIOD_CODE        75431 non-null   float64
 64  SALARY                      75434 non-null   float64
 65  REDUCE_SALARY_COUSE_CORONA  0 non-null       float64
 66  REDUCE_RATIO                0 non-null       float64
 67  LABOR_FORCE_B_CODE          20340 non-null   float64
 68  TOT_EMP                     3680 non-null    float64
 69  JOB_TARMEZ_CODE             79218 non-null   float64
 70  ACT_TARMEZ_CODE             79219 non-null   float64
 71  WORK_SECOND_CODE            79218 non-null   float64
 72  PLACE_CODE                  20340 non-null   float64
 73  WORK_SECOND                 1637 non-null    str
 74  ACT_SECOND                  1660 non-null    str
 75  SECOND_HOUR_NO              1637 non-null    float64
 76  NET_SALARY_SECOND           1637 non-null    float64
 77  REASON_HOUR35_CODE          2028 non-null    float64
 78  GIVER_CODE                  181983 non-null  float64
 79  AGE_CODE                    181980 non-null  float64
 80  DESIRE_WORK_CODE            104967 non-null  float64
 81  NO_DESIRE_CODE              172293 non-null  float64
 82  MAIN_REASON_NO_SEARCH_CODE  4269 non-null    float64
 83  SECTOR_CODE                 2216 non-null    float64
 84  HOUR_CONSUME_1_NO           2125 non-null    float64
 85  HOUR_CONSUME_2_NO           6088 non-null    float64
 86  HOUR_CONSUME_3_NO           618 non-null     float64
 87  HOUR_CONSUME_4_NO           874 non-null     float64
 88  HOUR_CONSUME_5_NO           21750 non-null   float64
 89  HOUR_CONSUME_6_NO           1362 non-null    float64
 90  HOUR_CONSUME_7_NO           81 non-null      float64
 91  HOUR_CONSUME_8_NO           457 non-null     float64
 92  HOUR_CONSUME_9_NO           43 non-null      float64
dtypes: float64(72), int64(9), object(1), str(11)
memory usage: 210.5+ MB

In [13]:
df.drop(
    columns = [col for col in df.columns if 'HOUR_CONSUME' in col],
    inplace = True
)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 84 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RESPONSEID                  296724 non-null  str
 1   PARENTRESPONSEID            296724 non-null  str
 2   DOMAINID                    296724 non-null  str
 3   PHASEID                     296724 non-null  str
 4   CREATIONPHASEID             296724 non-null  str
 5   GOV_CODE                    296724 non-null  int64
 6   STATION_CODE                296724 non-null  int64
 7   SECTION_CODE                296724 non-null  int64
 8   UR_CODE                     296724 non-null  float64
 9   MEMBER_CODE                 296724 non-null  object
 10  GIVER_NAME                  296724 non-null  int64
 11  RELATION_CODE               296724 non-null  int64
 12  GENDER_CODE                 296724 non-null  int64
 13  CURRENT_YEAR                296724 non-null  int64
 14  BIRTH_MONTH                 296723 non-null  float64
 15  BIRTH_YEAR                  296722 non-null  float64
 16  REAL_AGE                    296724 non-null  int64
 17  AGE                         296724 non-null  int64
 18  EDUCATION_JOIN_CODE         261200 non-null  float64
 19  EDU_LEAVE_REASON_CODE       78477 non-null   float64
 20  STAGE_CODE                  129797 non-null  float64
 21  GRADE                       129593 non-null  float64
 22  STAGE_CODE1                 0 non-null       float64
 23  EDU_CODE                    261200 non-null  float64
 24  EDUCATION_CODE              90468 non-null   str
 25  QUALIFICATION_CODE          90468 non-null   str
 26  QUALIFICATION_YEAR          90468 non-null   float64
 27  STUDY_YEAR_NO               0 non-null       float64
 28  MARITAL_CODE                235485 non-null  float64
 29  UNEDUCATED_CODE             0 non-null       float64
 30  TRAINING_COURSE_CODE        58358 non-null   float64
 31  PLACE_COURSE_CODE           509 non-null     float64
 32  COURSE_SUBJECT_CODE         509 non-null     float64
 33  COURSE_PERIOD               509 non-null     float64
 34  REASON_TRAINING_CODE        509 non-null     float64
 35  DIFFICULTIES                67013 non-null   float64
 36  SIGHT_CODE                  5258 non-null    float64
 37  HEARING_CODE                5258 non-null    float64
 38  MEMORY_CODE                 5258 non-null    float64
 39  WALKING_CODE                5258 non-null    float64
 40  SELFCARE_CODE               5258 non-null    float64
 41  CURRENTLY_SMOKING_CODE      49492 non-null   float64
 42  EDU_TRMEZ_CODE              90462 non-null   float64
 43  GIVER_NAME_E                261200 non-null  float64
 44  WORK_LAST_WEEK_CODE         261200 non-null  float64
 45  PAID_WORK_CODE              182898 non-null  float64
 46  EVER_WORK_CODE              79218 non-null   float64
 47  DESCRIPWORKCONDITION        79218 non-null   float64
 48  LABOR_FORCE_CODE            79218 non-null   float64
 49  GETYOURCLIENTS              76421 non-null   float64
 50  WORK_PLACE_CODE             79218 non-null   float64
 51  SECTOR_CODE_1               79218 non-null   float64
 52  ACT_OUT_EST                 79218 non-null   str
 53  CURRENT_WORK                79217 non-null   str
 54  START_WORKING               79218 non-null   float64
 55  REDUCE_DAYWORK_CORONA       0 non-null       float64
 56  HOUR_NO                     79218 non-null   float64
 57  INSURANCE_CODE              79218 non-null   float64
 58  INSURANCE_HEALTH_CODE       79218 non-null   float64
 59  VACATIONS_CODE              57021 non-null   float64
 60  WORK_NATURE_CODE            79218 non-null   float64
 61  CONTRACT_CODE               44156 non-null   float64
 62  BACK_208                    79218 non-null   float64
 63  EXCHANGE_PERIOD_CODE        75431 non-null   float64
 64  SALARY                      75434 non-null   float64
 65  REDUCE_SALARY_COUSE_CORONA  0 non-null       float64
 66  REDUCE_RATIO                0 non-null       float64
 67  LABOR_FORCE_B_CODE          20340 non-null   float64
 68  TOT_EMP                     3680 non-null    float64
 69  JOB_TARMEZ_CODE             79218 non-null   float64
 70  ACT_TARMEZ_CODE             79219 non-null   float64
 71  WORK_SECOND_CODE            79218 non-null   float64
 72  PLACE_CODE                  20340 non-null   float64
 73  WORK_SECOND                 1637 non-null    str
 74  ACT_SECOND                  1660 non-null    str
 75  SECOND_HOUR_NO              1637 non-null    float64
 76  NET_SALARY_SECOND           1637 non-null    float64
 77  REASON_HOUR35_CODE          2028 non-null    float64
 78  GIVER_CODE                  181983 non-null  float64
 79  AGE_CODE                    181980 non-null  float64
 80  DESIRE_WORK_CODE            104967 non-null  float64
 81  NO_DESIRE_CODE              172293 non-null  float64
 82  MAIN_REASON_NO_SEARCH_CODE  4269 non-null    float64
 83  SECTOR_CODE                 2216 non-null    float64
dtypes: float64(63), int64(9), object(1), str(11)
memory usage: 190.2+ MB

In [15]:
df.isna().sum() / len(df) * 100

RESPONSEID                     0.000000
PARENTRESPONSEID               0.000000
DOMAINID                       0.000000
PHASEID                        0.000000
CREATIONPHASEID                0.000000
                                ...
AGE_CODE                      38.670279
DESIRE_WORK_CODE              64.624702
NO_DESIRE_CODE                41.934929
MAIN_REASON_NO_SEARCH_CODE    98.561289
SECTOR_CODE                   99.253178
Length: 84, dtype: float64

In [16]:
columns_to_remove = [
    'EXCHANGE_PERIOD_CODE',
    'MEMBER_CODE',
    'GIVER_NAME',
    'CURRENT_YEAR',
    'BIRTH_MONTH',
    'GRADE',
    'QUALIFICATION_CODE',
    'STUDY_YEAR_NO',
    'UNEDUCATED_CODE',
]

In [17]:
df.drop(columns=columns_to_remove, inplace=True)

In [18]:
df['EDUCATION_CODE'].value_counts()

EDUCATION_CODE
دبلوم تجارة                 9715
دبلوم صنايع                 8182
دبلوم تجاره                 6305
دبلوم صناعى                 5111
دبلوم صناعي                 4680
                            ...
يكالوريوس حاسب الى             1
معهد سيارحه وفنادق             1
بكالوريوس معهد تكنولوجيا       1
معهد فنى تجار                  1
بكالوريوس تربوى                1
Name: count, Length: 4477, dtype: int64

In [19]:
df.shape

(296724, 75)

In [20]:
missing = df.isna().sum() / len(df) * 100
missing[missing > 0]

BIRTH_YEAR                      0.000674
EDUCATION_JOIN_CODE            11.972068
EDU_LEAVE_REASON_CODE          73.552190
STAGE_CODE                     56.256656
STAGE_CODE1                   100.000000
                                 ...
AGE_CODE                       38.670279
DESIRE_WORK_CODE               64.624702
NO_DESIRE_CODE                 41.934929
MAIN_REASON_NO_SEARCH_CODE     98.561289
SECTOR_CODE                    99.253178
Length: 62, dtype: float64

In [21]:
eq = 0
for i in range(len(df)):
    if df.loc[i, 'REAL_AGE'] == df['REAL_AGE'].iloc[i]:
        eq += 1
print(f"Total matching rows: {eq}")

Total matching rows: 296724

In [22]:
df[df['REAL_AGE'] < 0]

,RESPONSEID,PARENTRESPONSEID,DOMAINID,PHASEID,CREATIONPHASEID,GOV_CODE,STATION_CODE,SECTION_CODE,UR_CODE,RELATION_CODE,...,ACT_SECOND,SECOND_HOUR_NO,NET_SALARY_SECOND,REASON_HOUR35_CODE,GIVER_CODE,AGE_CODE,DESIRE_WORK_CODE,NO_DESIRE_CODE,MAIN_REASON_NO_SEARCH_CODE,SECTOR_CODE
87,43554497-0460-418B-BD5F-23C1DE058411,B772F33A-18C5-4342-8C84-504371C22C81,BAEBBCC6-5B35-4E68-AD86-64EEE8A1CD45,8F361C32-E757-4471-860B-3426BC5A5FBC,8F361C32-E757-4471-860B-3426BC5A5FBC,26,2603,260317,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,CF520FC3-E503-4D20-BDF4-191F21EACEDF,967ADBC0-91BA-4D4C-B5E9-B9F372C19DC0,3D1C8C41-CF9B-484B-A601-3119BBD8016C,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,22,2202,220211,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,2C04D274-BA19-4021-B3D4-2D903DA86418,E1904D57-884F-43F8-A839-87638658FB77,BFB250FB-192E-4092-A1AE-C5E2478FDAE6,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,18,1803,180309,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,2030E6DA-C17E-44D0-BBF1-C4A978BDD441,7E72D7DE-7E23-4BCC-BBE8-89C236EAF119,5AFE8594-A04E-4CE8-B12F-20BA16BBFD13,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,18,1813,181333,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2297,0F7B30D4-6860-45BF-BED7-28EE0332C21A,B981F72E-D703-4C2F-B185-A9852BDC4648,A068F396-C38E-4E13-9474-9CB6AB41A7D4,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,13,1306,130612,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296119,423FEBF3-4EDD-46B6-B39B-24F7F849F529,C3C8B0AF-F110-4767-AF3F-102802734FBD,7D7EE567-B882-48B1-9917-D43F00CE6C10,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,24,2412,241202,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296327,A80214E3-5C3E-48AD-8A24-731F22294789,40E97013-0C01-4DB6-BE9D-CFF167A784D4,5DD94606-D305-4C1E-961F-969B82232B8B,B7C88E4B-93C3-4CC8-B284-134514819194,B7C88E4B-93C3-4CC8-B284-134514819194,12,1204,120416,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296350,4E35C650-94F6-45E6-AC7D-2A048AD7E669,FC6A376A-4ED3-4A00-9F2E-45BC93C7A1FE,47EB4548-3D88-4710-B84E-B0DFD4C5C3AE,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,15,1508,150812,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296460,275E7455-01B2-48C0-A7A9-DFD8800F5844,CB4D3ACE-2677-4FA0-AC96-837900F99065,86FB76CF-7B9F-4D8C-AD0D-7C2989A2F1BD,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,19,1902,190203,1.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296508,69004EF2-FF5A-4730-92D3-95906D9456E7,59B97AA1-08AE-483F-A47D-A4FD41C8E6E6,6E4C3FB2-185E-4118-AE47-87089CFBA829,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,23,2302,230218,2.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.drop(columns = 'REAL_AGE', inplace = True)

In [24]:
df.drop(columns='AGE_CODE', inplace=True)

In [25]:
df.shape

(296724, 73)

In [26]:
df['EDUCATION_JOIN_CODE'] = df.loc[df['EDUCATION_JOIN_CODE'].isna() & (df['AGE'] < 20), 'EDUCATION_JOIN_CODE'] = 1

In [27]:
df.to_csv(r"D:\ITI\FinalProject\data\my_cleansed_df.csv")