In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'D:\ITI\FinalProject\data\member_info_2024_last.csv')
df

C:\Users\abdel\AppData\Local\Temp\ipykernel_20640\2102927505.py:1: DtypeWarning: Columns (0: MEMBER_CODE, 1: EDU_LEAVE_REASON_OTHER, 2: PLACE_COURSE_OTHER, 3: COURSE_SUBJECT_OTHER, 4: REASON_TRAINING_OTHER, 5: PREV_CHANGE_REASON_OTHER, 6: WORK_PREVENT_REASON_OTHER, 7: SECTOR_OTHER_1, 8: TEXT_229_I_H, 9: WORK_SECOND_TARMEZ, 10: PLACE_OTHER, 11: SEARCH_WORK_FIRST_OTHER, 12: SEARCH_WORK_SECOND_OTHER, 13: MAIN_REASON_NO_SEARCH_OTHER, 14: SECTOR_OTHER, 15: REASON_STOP_WORK_OTHER, 16: UNPAID_WORK_TYPE) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'D:\ITI\FinalProject\data\member_info_2024_last.csv')

,RESPONSEID,PARENTRESPONSEID,DOMAINID,PHASEID,CREATIONPHASEID,GOV_CODE,STATION_CODE,SECTION_CODE,UR_CODE,MEMBER_CODE,...,ACT_SECOND_TARMEZ,EMP_CODE,EMP_CODE_1,EMP_CODE_2,EMP_CODE_3,EMP_CODE_4,ORIGINAL,NORMAL,QUARTER,ORIGINAL_QUARTER
0,31AE82A8-95D7-4E66-876D-8031121996A2,9A9D8DC8-9355-4128-9164-D260852720BF,F5F1BE0A-C2D1-4DFE-9ACC-3DA0C151F80E,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,4,404,40401,1.0,1,...,NaN,1.0,1.0,NaN,NaN,NaN,224.842430,0.158556,1.0,899.369721
1,FCDE46DA-77B1-499D-A3A2-84B87E19E85E,CB34CB01-2F0E-4C0D-A11D-E6357E8727AF,E3DD23B1-0560-4AAB-997A-1350432F71DE,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,18,1809,180918,2.0,2,...,NaN,3.0,NaN,NaN,1.0,NaN,383.212208,0.270237,1.0,1532.848834
2,189336B9-6857-49C6-836D-C54AC6C2BEE9,068B1966-C39F-4BF2-92DE-1D52C947025D,0FD12B99-88F0-4A60-9FBC-83E71FEFD750,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,21,2105,210503,1.0,5,...,NaN,2.0,NaN,1.0,NaN,NaN,431.231027,0.304099,1.0,1724.924109
3,1512A995-F9F6-4369-A967-6806B446B1F2,97358DDF-DF60-4406-8C95-0C62B0CF6E01,3DFDF17A-5F59-40E7-97D6-17C0FBB71126,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,15,1502,150201,1.0,4,...,NaN,3.0,NaN,NaN,1.0,NaN,336.670043,0.237416,1.0,1346.680171
4,B6AC1F0E-C2AD-458C-BA2A-7A4026C03027,52CDDE65-7225-4717-BB8A-D1F713ADD602,7C5ADABA-56A3-41A2-A1F3-10B442F9C8DB,708C5ECF-9840-4521-B25D-94294CC0CAF8,708C5ECF-9840-4521-B25D-94294CC0CAF8,17,1705,170522,2.0,3,...,NaN,4.0,NaN,NaN,NaN,1.0,200.729200,0.141552,1.0,802.916802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296719,EC9B3617-2A83-4BF5-AC76-12BA0C8F488D,8DB7A2D8-5474-4936-8931-F2D106D4D970,6D2E6957-4FF4-4395-912B-6B4AB2054A11,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,14,1411,141102,1.0,4,...,NaN,3.0,NaN,NaN,1.0,NaN,376.372437,0.261558,4.0,1505.489749
296720,05AE321C-908A-48B9-B785-4ED4C0A6DE8F,76B18629-8A0A-4135-92EA-29DE75088EF5,63DE7D74-CB10-469E-A652-4A137DD78B4C,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,21,2111,211110,2.0,2,...,NaN,3.0,NaN,NaN,1.0,NaN,478.115213,0.332263,4.0,1912.460852
296721,411B88A4-C384-4B03-BCCF-4EEC8AB08495,9408D533-A347-4CBC-ADD7-4C15906A1720,6C799CC3-D409-4CEC-B54A-F00A995086C5,B7C88E4B-93C3-4CC8-B284-134514819194,B7C88E4B-93C3-4CC8-B284-134514819194,25,2514,251401,1.0,2,...,NaN,3.0,NaN,NaN,1.0,NaN,376.486389,0.261637,4.0,1505.945556
296722,665DAA91-B90A-4A81-A612-4F4FC284BA34,0E79D069-08A2-46C5-B062-50DB7522E7E3,D28461CE-642E-477E-8A1D-E59607C5E168,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,17,1704,170401,1.0,1,...,NaN,1.0,1.0,NaN,NaN,NaN,468.601159,0.325652,4.0,1874.404636
296723,FC5696A6-6A8E-4AB2-A49B-02FFC449ABBD,9AA32D23-A6D4-476E-99F1-DD7866C6A416,F7ABEE76-EFA9-4CBD-AE27-DF3E77298720,81604C51-0A8C-456C-AE77-33380BE69716,81604C51-0A8C-456C-AE77-33380BE69716,13,1305,130508,2.0,1,...,NaN,1.0,1.0,NaN,NaN,NaN,433.768005,0.301445,4.0,1735.072020

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Columns: 235 entries, RESPONSEID to ORIGINAL_QUARTER
dtypes: float64(194), int64(9), object(2), str(30)
memory usage: 532.0+ MB

In [4]:
df.columns.astype('object')

Index(['RESPONSEID', 'PARENTRESPONSEID', 'DOMAINID', 'PHASEID',
       'CREATIONPHASEID', 'GOV_CODE', 'STATION_CODE', 'SECTION_CODE',
       'UR_CODE', 'MEMBER_CODE',
       ...
       'ACT_SECOND_TARMEZ', 'EMP_CODE', 'EMP_CODE_1', 'EMP_CODE_2',
       'EMP_CODE_3', 'EMP_CODE_4', 'ORIGINAL', 'NORMAL', 'QUARTER',
       'ORIGINAL_QUARTER'],
      dtype='object', length=235)

In [5]:
threshold = 50
(df.isna().sum() / len(df) * 100).where(lambda x: x > threshold)

RESPONSEID                NaN
PARENTRESPONSEID          NaN
DOMAINID                  NaN
PHASEID                   NaN
CREATIONPHASEID           NaN
                      ...
EMP_CODE_4          83.173926
ORIGINAL                  NaN
NORMAL                    NaN
QUARTER                   NaN
ORIGINAL_QUARTER          NaN
Length: 235, dtype: float64

In [6]:
df['NAME_PERSON_FAMILY'].nunique()

0

In [7]:
df.drop(columns = df.columns[df.isna().sum() == len(df)], inplace = True)

In [8]:
df.shape

(296724, 204)

In [9]:
df.drop(
    columns = df.columns[(df.isna().sum() / len(df) * 100) > 75],
    inplace = True
)

In [10]:
df.shape

(296724, 72)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 72 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   RESPONSEID             296724 non-null  str
 1   PARENTRESPONSEID       296724 non-null  str
 2   DOMAINID               296724 non-null  str
 3   PHASEID                296724 non-null  str
 4   CREATIONPHASEID        296724 non-null  str
 5   GOV_CODE               296724 non-null  int64
 6   STATION_CODE           296724 non-null  int64
 7   SECTION_CODE           296724 non-null  int64
 8   UR_CODE                296724 non-null  float64
 9   MEMBER_CODE            296724 non-null  object
 10  GIVER_NAME             296724 non-null  int64
 11  RELATION_CODE          296724 non-null  int64
 12  GENDER_CODE            296724 non-null  int64
 13  CURRENT_YEAR           296724 non-null  int64
 14  BIRTH_MONTH            296723 non-null  float64
 15  BIRTH_YEAR             296722 non-null  float64
 16  REAL_AGE               296724 non-null  int64
 17  AGE                    296724 non-null  int64
 18  EDUCATION_JOIN_CODE    261200 non-null  float64
 19  EDU_LEAVE_REASON_CODE  78477 non-null   float64
 20  STAGE_CODE             129797 non-null  float64
 21  GRADE                  129593 non-null  float64
 22  EDU_CODE               261200 non-null  float64
 23  EDUCATION_CODE         90468 non-null   str
 24  QUALIFICATION_CODE     90468 non-null   str
 25  QUALIFICATION_YEAR     90468 non-null   float64
 26  MARITAL_CODE           235485 non-null  float64
 27  EDU_TRMEZ_CODE         90462 non-null   float64
 28  GIVER_NAME_E           261200 non-null  float64
 29  WORK_LAST_WEEK_CODE    261200 non-null  float64
 30  PAID_WORK_CODE         182898 non-null  float64
 31  MARKET_CONSUM_1        182455 non-null  float64
 32  MARKET_CONSUM_2        182455 non-null  float64
 33  MARKET_CONSUM_3        182455 non-null  float64
 34  MARKET_CONSUM_4        182504 non-null  float64
 35  MARKET_CONSUM_5        182504 non-null  float64
 36  MARKET_CONSUM_6        182504 non-null  float64
 37  MARKET_CONSUM_7        182504 non-null  float64
 38  MARKET_CONSUM_8        182504 non-null  float64
 39  MARKET_CONSUM_9        182504 non-null  float64
 40  MARKET_CONSUM_10       182504 non-null  float64
 41  MARKET_CONSUM_11       182504 non-null  float64
 42  EVER_WORK_CODE         79218 non-null   float64
 43  DESCRIPWORKCONDITION   79218 non-null   float64
 44  LABOR_FORCE_CODE       79218 non-null   float64
 45  GETYOURCLIENTS         76421 non-null   float64
 46  WORK_PLACE_CODE        79218 non-null   float64
 47  SECTOR_CODE_1          79218 non-null   float64
 48  ACT_OUT_EST            79218 non-null   str
 49  CURRENT_WORK           79217 non-null   str
 50  START_WORKING          79218 non-null   float64
 51  HOUR_NO                79218 non-null   float64
 52  INSURANCE_CODE         79218 non-null   float64
 53  INSURANCE_HEALTH_CODE  79218 non-null   float64
 54  WORK_NATURE_CODE       79218 non-null   float64
 55  BACK_208               79218 non-null   float64
 56  EXCHANGE_PERIOD_CODE   75431 non-null   float64
 57  SALARY                 75434 non-null   float64
 58  JOB_TARMEZ_CODE        79218 non-null   float64
 59  ACT_TARMEZ_CODE        79219 non-null   float64
 60  WORK_SECOND_CODE       79218 non-null   float64
 61  GIVER_CODE             181983 non-null  float64
 62  AGE_CODE               181980 non-null  float64
 63  DESIRE_WORK_CODE       104967 non-null  float64
 64  NO_DESIRE_CODE         172293 non-null  float64
 65  EMP_CODE               296724 non-null  float64
 66  EMP_CODE_1             79218 non-null   float64
 67  EMP_CODE_3             162159 non-null  float64
 68  ORIGINAL               296724 non-null  float64
 69  NORMAL                 296724 non-null  float64
 70  QUARTER                296724 non-null  float64
 71  ORIGINAL_QUARTER       296724 non-null  float64
dtypes: float64(53), int64(9), object(1), str(9)
memory usage: 163.0+ MB

In [12]:
(df.isna().sum() / len(df) * 100 > 50).sum()

np.int64(28)

In [13]:
df.sample(10)

,RESPONSEID,PARENTRESPONSEID,DOMAINID,PHASEID,CREATIONPHASEID,GOV_CODE,STATION_CODE,SECTION_CODE,UR_CODE,MEMBER_CODE,...,AGE_CODE,DESIRE_WORK_CODE,NO_DESIRE_CODE,EMP_CODE,EMP_CODE_1,EMP_CODE_3,ORIGINAL,NORMAL,QUARTER,ORIGINAL_QUARTER
173521,93E07AF2-310E-41BB-8EB9-E8A6E6BE6F61,61ED6C0A-BDF3-46D1-9271-79CE4C563CEA,9B4E2086-071E-4258-BB85-A4872B7D9057,EF558B44-CA92-4573-BB5E-37C375DE8673,EF558B44-CA92-4573-BB5E-37C375DE8673,13,1314,131401,1.0,2,...,1.0,2.0,3.0,3.0,NaN,1.0,429.853442,0.297220,3.0,1719.413766
49834,CF5B11F3-F7B3-486E-926B-9F2A06BEF772,439E34A8-5E89-4E4F-9F8C-48200FBBE1E4,64462A8D-685B-436E-821C-3A238D9D7688,16C2B15F-146B-435B-ACB8-D3C2C7606750,16C2B15F-146B-435B-ACB8-D3C2C7606750,18,1814,181455,2.0,1,...,1.0,2.0,5.0,3.0,NaN,1.0,386.277705,0.272399,1.0,1545.110821
217232,C25D3306-FE15-4027-AD21-E87F99207361,73E1AA53-F0F7-4F0A-9E1B-412A45F2B252,82AAF4E9-40F9-450A-AA02-6299D78967B8,A30DA09A-E1E2-41F9-A693-4BE503D86D4A,A30DA09A-E1E2-41F9-A693-4BE503D86D4A,32,3205,320533,2.0,1,...,NaN,NaN,NaN,1.0,1.0,NaN,146.983048,0.101631,3.0,587.932191
89597,FC0E237C-EF7A-49E3-B5E1-20F137EED902,BDD0343C-4AAB-479B-B5E7-B839DADC9021,9736A046-302C-410A-BAED-BA93761C5093,F76B89A2-53E5-43DD-8284-18B3E7477B1D,F76B89A2-53E5-43DD-8284-18B3E7477B1D,16,1611,161116,2.0,5,...,1.0,2.0,4.0,3.0,NaN,1.0,345.592861,0.241947,2.0,1382.371442
241473,A41A477C-5341-449D-904E-B6702086AC08,253CAFD7-9003-4E19-AC43-9A4A05DF3258,5E082ECE-8D20-4D07-9DDE-82C9AD0A3D86,D106948E-9848-4494-9CFF-4523A8926D2B,D106948E-9848-4494-9CFF-4523A8926D2B,23,2306,230621,2.0,3,...,2.0,NaN,4.0,3.0,NaN,1.0,269.750839,0.187462,4.0,1079.003354
287820,48103921-B036-4092-8C13-B3877D83B62B,951634D9-A4F0-44C0-86CC-CA37CEB9EF87,E3DD23B1-0560-4AAB-997A-1350432F71DE,B7C88E4B-93C3-4CC8-B284-134514819194,B7C88E4B-93C3-4CC8-B284-134514819194,18,1809,180918,2.0,3,...,2.0,NaN,4.0,3.0,NaN,1.0,311.899879,0.216753,4.0,1247.599517
31531,150BAEB5-C370-4B05-BE9D-B469A00B13B6,1C8C7575-52DD-420F-9C34-48FC5BA11D10,A9A8AF68-CD06-4AFD-9252-A10BEBBFC1EF,16C2B15F-146B-435B-ACB8-D3C2C7606750,16C2B15F-146B-435B-ACB8-D3C2C7606750,13,1311,131129,2.0,2,...,1.0,1.0,3.0,3.0,NaN,1.0,383.283491,0.270287,1.0,1533.133964
175620,B179C07F-90FB-4BB2-93A8-8F2EBE8A84DE,90BFAD81-3F65-4203-A820-A10E035C8D72,64A7C761-8BF0-4D3E-A004-549E19432411,10EEA6CC-C3D3-48E4-8092-073C9F5CCF56,10EEA6CC-C3D3-48E4-8092-073C9F5CCF56,23,2302,230224,2.0,5,...,2.0,NaN,4.0,3.0,NaN,1.0,280.135774,0.193698,3.0,1120.543098
28974,21EC8F58-9C11-4B3D-A841-BC9300C54DED,47CF4C66-6794-4CA0-91EF-7F9EE05BBAF3,8EFE1462-F6AB-4444-9F10-5D572F5D1D45,16C2B15F-146B-435B-ACB8-D3C2C7606750,16C2B15F-146B-435B-ACB8-D3C2C7606750,3,303,30301,1.0,2,...,1.0,2.0,3.0,3.0,NaN,1.0,231.622904,0.163338,1.0,926.491614
58691,0F27254F-65C2-4FA9-9D62-4C06C5B1FFC1,39878602-F3C7-45C5-9E23-F0511CE23E60,C0D0650C-BFA2-40C2-BD8F-AD1DDE048911,720F2ADB-B538-42B0-8885-9DB38E238976,720F2ADB-B538-42B0-8885-9DB38E238976,17,1704,170436,2.0,2,...,2.0,NaN,4.0,3.0,NaN,1.0,340.730051,0.240279,1.0,1362.920204

In [14]:
df.drop(
    columns = df.columns[(df.isna().sum() / len(df) * 100) > 50],
    inplace = True
)

In [15]:
df.shape

(296724, 44)

In [16]:
df.isna().sum() / len(df) * 100

RESPONSEID              0.000000
PARENTRESPONSEID        0.000000
DOMAINID                0.000000
PHASEID                 0.000000
CREATIONPHASEID         0.000000
GOV_CODE                0.000000
STATION_CODE            0.000000
SECTION_CODE            0.000000
UR_CODE                 0.000000
MEMBER_CODE             0.000000
GIVER_NAME              0.000000
RELATION_CODE           0.000000
GENDER_CODE             0.000000
CURRENT_YEAR            0.000000
BIRTH_MONTH             0.000337
BIRTH_YEAR              0.000674
REAL_AGE                0.000000
AGE                     0.000000
EDUCATION_JOIN_CODE    11.972068
EDU_CODE               11.972068
MARITAL_CODE           20.638371
GIVER_NAME_E           11.972068
WORK_LAST_WEEK_CODE    11.972068
PAID_WORK_CODE         38.360901
MARKET_CONSUM_1        38.510198
MARKET_CONSUM_2        38.510198
MARKET_CONSUM_3        38.510198
MARKET_CONSUM_4        38.493684
MARKET_CONSUM_5        38.493684
MARKET_CONSUM_6        38.493684
MARKET_CONSUM_7        38.493684
MARKET_CONSUM_8        38.493684
MARKET_CONSUM_9        38.493684
MARKET_CONSUM_10       38.493684
MARKET_CONSUM_11       38.493684
GIVER_CODE             38.669268
AGE_CODE               38.670279
NO_DESIRE_CODE         41.934929
EMP_CODE                0.000000
EMP_CODE_3             45.350224
ORIGINAL                0.000000
NORMAL                  0.000000
QUARTER                 0.000000
ORIGINAL_QUARTER        0.000000
dtype: float64

In [17]:
df.drop(columns = df.columns[df.columns.str.contains('MARKET_CONSUM')], inplace = True)

In [18]:
df.shape

(296724, 33)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   RESPONSEID           296724 non-null  str
 1   PARENTRESPONSEID     296724 non-null  str
 2   DOMAINID             296724 non-null  str
 3   PHASEID              296724 non-null  str
 4   CREATIONPHASEID      296724 non-null  str
 5   GOV_CODE             296724 non-null  int64
 6   STATION_CODE         296724 non-null  int64
 7   SECTION_CODE         296724 non-null  int64
 8   UR_CODE              296724 non-null  float64
 9   MEMBER_CODE          296724 non-null  object
 10  GIVER_NAME           296724 non-null  int64
 11  RELATION_CODE        296724 non-null  int64
 12  GENDER_CODE          296724 non-null  int64
 13  CURRENT_YEAR         296724 non-null  int64
 14  BIRTH_MONTH          296723 non-null  float64
 15  BIRTH_YEAR           296722 non-null  float64
 16  REAL_AGE             296724 non-null  int64
 17  AGE                  296724 non-null  int64
 18  EDUCATION_JOIN_CODE  261200 non-null  float64
 19  EDU_CODE             261200 non-null  float64
 20  MARITAL_CODE         235485 non-null  float64
 21  GIVER_NAME_E         261200 non-null  float64
 22  WORK_LAST_WEEK_CODE  261200 non-null  float64
 23  PAID_WORK_CODE       182898 non-null  float64
 24  GIVER_CODE           181983 non-null  float64
 25  AGE_CODE             181980 non-null  float64
 26  NO_DESIRE_CODE       172293 non-null  float64
 27  EMP_CODE             296724 non-null  float64
 28  EMP_CODE_3           162159 non-null  float64
 29  ORIGINAL             296724 non-null  float64
 30  NORMAL               296724 non-null  float64
 31  QUARTER              296724 non-null  float64
 32  ORIGINAL_QUARTER     296724 non-null  float64
dtypes: float64(18), int64(9), object(1), str(5)
memory usage: 74.7+ MB

In [20]:
df[['MARITAL_CODE', 'REAL_AGE', "AGE"]]

        MARITAL_CODE  REAL_AGE  AGE
0                3.0        38   38
1                3.0        37   37
2                1.0        28   28
3                NaN         9    9
4                5.0        80   80
...              ...       ...  ...
296719           1.0        19   19
296720           3.0        42   42
296721           3.0        25   25
296722           1.0        39   39
296723           3.0        31   31

[296724 rows x 3 columns]

In [21]:
age_less_18 = df[df['REAL_AGE'] < 18][['MARITAL_CODE', 'AGE', 'REAL_AGE']]
age_less_18

        MARITAL_CODE  AGE  REAL_AGE
3                NaN    9         9
7                7.0   16        16
23               NaN    1         1
31               NaN    8         8
32               7.0   14        14
...              ...  ...       ...
296704           7.0   16        16
296705           7.0   15        15
296707           NaN    7         7
296710           NaN    0         0
296713           NaN    3         3

[115150 rows x 3 columns]

In [22]:
age_less_18.isna().sum()

MARITAL_CODE    61238
AGE                 0
REAL_AGE            0
dtype: int64

In [23]:
df['MARITAL_CODE'].isna().sum()

np.int64(61239)

In [24]:
# df['MARITAL_CODE'] = df['MARITAL_CODE'].fillna(7).where(df['REAL_AGE'] < 18)

In [25]:
df['MARITAL_CODE'] = df.loc[df['MARITAL_CODE'].isna() & (df['REAL_AGE'] < 18), 'MARITAL_CODE'] = 7

In [26]:
df['MARITAL_CODE'].isna().sum()

np.int64(0)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   RESPONSEID           296724 non-null  str
 1   PARENTRESPONSEID     296724 non-null  str
 2   DOMAINID             296724 non-null  str
 3   PHASEID              296724 non-null  str
 4   CREATIONPHASEID      296724 non-null  str
 5   GOV_CODE             296724 non-null  int64
 6   STATION_CODE         296724 non-null  int64
 7   SECTION_CODE         296724 non-null  int64
 8   UR_CODE              296724 non-null  float64
 9   MEMBER_CODE          296724 non-null  object
 10  GIVER_NAME           296724 non-null  int64
 11  RELATION_CODE        296724 non-null  int64
 12  GENDER_CODE          296724 non-null  int64
 13  CURRENT_YEAR         296724 non-null  int64
 14  BIRTH_MONTH          296723 non-null  float64
 15  BIRTH_YEAR           296722 non-null  float64
 16  REAL_AGE             296724 non-null  int64
 17  AGE                  296724 non-null  int64
 18  EDUCATION_JOIN_CODE  261200 non-null  float64
 19  EDU_CODE             261200 non-null  float64
 20  MARITAL_CODE         296724 non-null  int64
 21  GIVER_NAME_E         261200 non-null  float64
 22  WORK_LAST_WEEK_CODE  261200 non-null  float64
 23  PAID_WORK_CODE       182898 non-null  float64
 24  GIVER_CODE           181983 non-null  float64
 25  AGE_CODE             181980 non-null  float64
 26  NO_DESIRE_CODE       172293 non-null  float64
 27  EMP_CODE             296724 non-null  float64
 28  EMP_CODE_3           162159 non-null  float64
 29  ORIGINAL             296724 non-null  float64
 30  NORMAL               296724 non-null  float64
 31  QUARTER              296724 non-null  float64
 32  ORIGINAL_QUARTER     296724 non-null  float64
dtypes: float64(17), int64(10), object(1), str(5)
memory usage: 74.7+ MB

In [28]:
df['EDUCATION_JOIN_CODE'].value_counts()

EDUCATION_JOIN_CODE
5.0    92595
4.0    90128
1.0    38807
3.0    36754
2.0     2916
Name: count, dtype: int64

In [29]:
df['REAL_AGE'] = df["REAL_AGE"].replace(-1, 0)

In [30]:
edu_code = df[df['EDUCATION_JOIN_CODE'].isna() & (df['REAL_AGE'] < 20)][['EDUCATION_JOIN_CODE', 'REAL_AGE', 'AGE']]

In [31]:
edu_code['AGE'].value_counts()

AGE
5    8014
4    6537
3    6230
2    5202
0    5105
1    4436
Name: count, dtype: int64

In [32]:
df['EDUCATION_JOIN_CODE'] = df.loc[df['EDUCATION_JOIN_CODE'].isna() & (df['REAL_AGE'] < 20), 'EDUCATION_JOIN_CODE'] = 1

In [33]:
miss = df[df['REAL_AGE'] < 0]
miss['REAL_AGE'].value_counts()

Series([], Name: count, dtype: int64)

In [34]:
miss[['REAL_AGE', 'AGE']]

Empty DataFrame
Columns: [REAL_AGE, AGE]
Index: []

In [35]:
# df['REAL_AGE'] = df["REAL_AGE"].replace(-1, 0)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 296724 entries, 0 to 296723
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   RESPONSEID           296724 non-null  str
 1   PARENTRESPONSEID     296724 non-null  str
 2   DOMAINID             296724 non-null  str
 3   PHASEID              296724 non-null  str
 4   CREATIONPHASEID      296724 non-null  str
 5   GOV_CODE             296724 non-null  int64
 6   STATION_CODE         296724 non-null  int64
 7   SECTION_CODE         296724 non-null  int64
 8   UR_CODE              296724 non-null  float64
 9   MEMBER_CODE          296724 non-null  object
 10  GIVER_NAME           296724 non-null  int64
 11  RELATION_CODE        296724 non-null  int64
 12  GENDER_CODE          296724 non-null  int64
 13  CURRENT_YEAR         296724 non-null  int64
 14  BIRTH_MONTH          296723 non-null  float64
 15  BIRTH_YEAR           296722 non-null  float64
 16  REAL_AGE             296724 non-null  int64
 17  AGE                  296724 non-null  int64
 18  EDUCATION_JOIN_CODE  296724 non-null  int64
 19  EDU_CODE             261200 non-null  float64
 20  MARITAL_CODE         296724 non-null  int64
 21  GIVER_NAME_E         261200 non-null  float64
 22  WORK_LAST_WEEK_CODE  261200 non-null  float64
 23  PAID_WORK_CODE       182898 non-null  float64
 24  GIVER_CODE           181983 non-null  float64
 25  AGE_CODE             181980 non-null  float64
 26  NO_DESIRE_CODE       172293 non-null  float64
 27  EMP_CODE             296724 non-null  float64
 28  EMP_CODE_3           162159 non-null  float64
 29  ORIGINAL             296724 non-null  float64
 30  NORMAL               296724 non-null  float64
 31  QUARTER              296724 non-null  float64
 32  ORIGINAL_QUARTER     296724 non-null  float64
dtypes: float64(16), int64(11), object(1), str(5)
memory usage: 74.7+ MB

In [37]:
df['row_id'] = range(1, len(df) + 1)

In [38]:
# row by row comparison
eq = 0
for i in range(len(df)):
    if df.loc[i, 'REAL_AGE'] == df['REAL_AGE'].iloc[i]:
        eq += 1
print(f"Total matching rows: {eq}")

Total matching rows: 296724

In [39]:
df.drop(columns = 'REAL_AGE', inplace = True)

In [40]:
df.drop(columns = 'AGE_CODE', inplace = True)

In [41]:
df.shape

(296724, 32)

In [45]:
df.to_csv(r'D:\ITI\FinalProject\data\cleaned_df.csv')

In [1]:
# columns_to_drop = [
#     'NAME_PERSON_FAMILY',
#     'NOTCHIL_REGISTERED_CD',
#     'NOT_PERSON_FAMILY_CODE',
#     'EDU_LEAVE_REASON_OTHER',
#     'GRADE1',
#     'MARITAL_CONFIRM_FEMALE',
#     'PLACE_COURSE_OTHER',
#     'COURSE_SUBJECT_OTHER',
#     'TRAINING_PERIOD_LESSMONTH',
#     'TIME_RECYCLE',
#     'REASON_TRAINING_OTHER',
#     'UNDERSTANDING_CODE',
#     'CHANGE_STAY_CODE',
#     'OUT_IN_CODE',
#     'PREV_PLACE_CODE',
#     'PREV_PLACE_OUT',
#     'PREV_CHANGE_YEAR',
#     'PREV_CHANGE_REASON_CODE',
#     'PREV_CHANGE_REASON_OTHER',
#     'LAST_SMOKING_CODE',
#     'LAST_DAY_SMOKING_CODE',
#     'EDU_TRMEZ_REVIEW_CODE',
#     'NOTICE',
#     'NOT_ANSWER_HIMSELF',
#     'PAID_WORK_TYPE_CODE',
#     'WORK_PREVENT_REASON',
#     'WORK_PREVENT_REASON_OTHER',
#     'ABSENT_DURATION',
#     'Q_204_A',
#     'DECISIOMAKER',
#     'HIRE_AWORKER_3MONTH',
#     'ENTITYPROVIDE',
#     'REGISTEREDOFFICIALRECORDS',
#     'MANAGEPROJECT',
#     'EST_NAME',
#     'WORK_TYPE_CODE',
#     'URCODE',
#     'SECTOR_OTHER_1',
#     'YEAR_NO',
#     'VACATIONS_ILLNESS_CODE',
#     'INDEMNITY_CODE',
#     'CONTRACT_PERIOD_CODE',
#     'FIXEDWAGE',
#     'PAYWORKCOMPLETED',
#     'COMMISSIONS',
#     'TIPPING_GRATUITY',
#     'FEES_EACHSERVICE',
#     'NON_FINANCIALCONSIDERATION',
#     'OTHER_229_H',
#     'TEXT_229_I_H',
#     'DONTGETPAID',
#     'EST_ACCOUNTING_CODE',
#     'EST_INDS_REG_COMM_CODE',
#     'EST_INSURANCE_CODE',
#     'WORK_ORG_FAM_CODE',
#     'WORK_SECOND_TARMEZ',
#     'TOT_EMP_CODE',
#     'EST_ACCOUN_SECOND_CODE',
#     'EST_INDS_REG_COM_SCND_CD',
#     'EST_INSURANCE_SCND_CODE',
#     'WRK_ORG_FAM_SCND_CODE',
#     'PLACE_OTHER',
#     'EXCH_PERIOD_SCND_CD',
#     'ADD_HOUR_NO',
#     'HOUR_SECOND_NO',
#     'ADD_HOUR_CODE',
#     'SRCH_PS_WK4_WRK_ADD_CD',
#     'SEARCH_WEEK4_WORK_CODE',
#     'COMMENT1',
#     'START_WORK_CODE',
#     'NO_DESIRE_OTHER',
#     'SEARCH_WORK_WITHOUT_LIMT',
#     'SEARCH_WORK_CODE',
#     'SEARCH_WORK_FIRST_CODE',
#     'SEARCH_WORK_FIRST',
#     'SEARCH_WORK_FIRST_OTHER',
#     'SEARCH_WORK_SECOND_CODE',
#     'SEARCH_WORK_SECOND',
#     'SEARCH_WORK_SECOND_OTHER',
#     'SEARCH_WORK_THIRD_CODE',
#     'SEARCH_WORK_THIRD',
#     'SEARCH_WORK_THIRD_OTHER',
#     'WORK_CODE',
#     'MAIN_REASON_NO_SEARCH_OTHER',
#     'GIVER_CODE_C',
#     'EVER_WORK_CODE_1',
#     'COMMENT_WRITE',
#     'LAST_WORK',
#     'LAST_ACT',
#     'SECTOR_OTHER',
#     'WORK_PLACE_CODE_CORONA',
#     'REASON_STOP_WORK_CODE',
#     'REASON_STOP_WORK_OTHER',
#     'STOP_WORK_COUSECORONA',
#     'STOP_WORK_MONTH',
#     'REFUSED_JOP',
#     'REFUSED_JOP_REASON_CODE',
#     'REFUSED_JOP_REASON_OTHER',
#     'PROBLEM_WORK_CODE',
#     'PROBLEM_WORK_OTHER',
#     'JOBTRZ_REV_CD_LST_WRK',
#     'JOB_TRMEZ_CODE_LAST_WORK',
#     'LST_ACT_TRZ_REV_CD',
#     'LAST_ACT_TRMEZ_CODE',
#     'GIVER_DESCRIPTION_CODE',
#     'PRACTICE_UNPAID_ACT_CODE',
#     'UNPAID_ACT_CODE',
#     'WORK_ENTITY_CODE',
#     'UNPAID_WORK_TYPE',
#     'MJORUNPAIDOCCUPATIONREV',
#     'MAINOCCUPUNPAIDINDVUA',
#     'UNPAID_HOUR_NO',
#     'ACT_SECOND_TARMEZ',
#     'ORIGINAL',
#     'NORMAL',
#     'QUARTER',
#     'ORIGINAL_QUARTER',
# ]

In [2]:
# HOUSE_CONSUME_ --> all this columns
# EMP_CODE --> all this columns